### ISSUE TITLE
This is harmful to humanity

### ISSUE THREAD

**Issue by KevinX8** [BEPISMAN2/FidgetSpinner3DS#1]
This will likely increase the suicide rates worldwide and you should be ashamed for being it's creator >:^)

**Comment by Kingy34** [comment]
this existing is an issue already tbh

**Comment by BEPISMAN2** [comment]
Y'all need some milk

**Comment by KevinX8** [comment]
Ew cultural appropriation of cows

**Comment by cheuble** [comment]
Milk is bad for you :^)
